version: '3.4'

services:
  im.access.admin:
    image: ${DOCKER_REGISTRY-}imaccessadmin
    ports:
      - 9000:80
    build:
      context: .
      dockerfile: src/Im.Access.Admin/Dockerfile
    container_name: im-access-admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__TenantConfigDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=http://127.0.0.1.xip.io:9000"
      - "AdminConfiguration__IdentityAdminRedirectUri=http://127.0.0.1.xip.io:9000/signin-oidc"
      - "AdminConfiguration__IdentityServerBaseUrl=http://127.0.0.1.xip.io:7000"
      - "AdminConfiguration__RequireHttpsMetadata=false"
      - "IdentityServerData__Clients__0__ClientUri=http://127.0.0.1.xip.io:9000"
      - "IdentityServerData__Clients__0__RedirectUris__0=http://127.0.0.1.xip.io:9000/signin-oidc"
      - "IdentityServerData__Clients__0__FrontChannelLogoutUri=http://127.0.0.1.xip.io:9000/signin-oidc"
      - "IdentityServerData__Clients__0__PostLogoutRedirectUris__0=http://127.0.0.1.xip.io:9000/signout-callback-oidc"
      - "IdentityServerData__Clients__0__AllowedCorsOrigins__0=http://127.0.0.1.xip.io:9000"
      - "IdentityServerData__Clients__1__RedirectUris__0=http://127.0.0.1.xip.io:5000/swagger/oauth2-redirect.html"
      - "Serilog__WriteTo__1__Args__connectionString=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    command: dotnet Im.Access.Admin.dll /seed
    depends_on:
      - db
      - im.access.portal

  im.access.admin.api:
    image: ${DOCKER_REGISTRY-}imaccessadminapi
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: src/Im.Access.Admin.Api/Dockerfile
    container_name: im-access-admin-api
    environment:
      - "AdminApiConfiguration__RequireHttpsMetadata=false"
      - "AdminApiConfiguration__IdentityServerBaseUrl=http://127.0.0.1.xip.io:7000"
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__TenantConfigDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    depends_on:
      - db
      - im.access.portal

  im.access.portal:
    image: ${DOCKER_REGISTRY-}imaccessportal
    ports:
      - 7000:80
    build:
      context: .
      dockerfile: src/Im.Access.Portal/Dockerfile
    container_name: im-access-portal
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__TenantConfigDbConnection=Server=db;Database=Im.Access;User Id=identityroot;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=http://127.0.0.1.xip.io:9000"
    depends_on:
      - db
    networks:
      default:
        aliases:
          - 127.0.0.1.xip.io
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
      - 1434:1434
    container_name: im-access-db
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-Password_123}"
      ACCEPT_EULA: "Y"
      TZ: "Europe/London"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
    driver: local

networks:
  default:
    driver: bridge